### ISSUE TITLE
Sometimes nothing loads for Flood Zone

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/property-buddy#9]
In some locations when I load the page the Flood Zone doesn't show anything. It should show a message about no results.

**Comment by wbprice** [comment]
<img width="608" alt="screen shot 2018-07-29 at 8 31 30 pm" src="https://user-images.githubusercontent.com/2590422/43372429-c47f6a88-936e-11e8-9486-50842d038f07.png">
